const session = require('express-session');
const PostgresSessionStore = require('connect-pg-simple')(session);

module.exports = {
	setup(app) {
		app.use(session({
			secret: process.env.SESSION_SECRET || 'some_random_chars_sagkdjghskldsgjkdsg',
			resave: false,
			saveUninitialized: false,
			store: new PostgresSessionStore({
			//	pg: pg
			//	"session" table (used by PostgresSessionStore must be created
			//	manually at the moment, it's not autogenerated. See how here:
			//	https://github.com/voxpelli/node-connect-pg-simple/blob/master/table.sql
				conString: process.env.DATABASE_URL // this is implicit, but let's keep it for reference
			}),
		}));
	}
}